import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Menu, Bell, User, ArrowLeft } from 'lucide-react';
import { useDashboard } from '../context/DashboardContext';
import { useAuth } from '../context/SupabaseAuthContext';
const Header = ({ onToggleSidebar, onBackToPublic }) => {
    const { userRole, setUserRole, notifications } = useDashboard();
    const { profile } = useAuth();
    return (_jsxs("header", { className: "bg-white shadow-sm p-4 flex items-center justify-between sticky top-0 z-20 glass-effect", children: [_jsxs("div", { className: "flex items-center", children: [onBackToPublic && (_jsx("button", { onClick: onBackToPublic, className: "mr-4 p-2 text-gray-600 hover:text-primary-600 transition-all duration-300 transform hover:scale-110", title: "Ana Siteye D\u00F6n", children: _jsx(ArrowLeft, { size: 24 }) })), _jsx("button", { onClick: onToggleSidebar, className: "mr-4 md:hidden text-gray-700 hover:text-primary-600 transition-all duration-300 transform hover:scale-110", "aria-label": "Yan men\u00FCy\u00FC a\u00E7/kapat", title: "Yan men\u00FCy\u00FC a\u00E7/kapat", children: _jsx(Menu, { size: 24 }) }), _jsx("h1", { className: "font-pacifico text-primary-600 text-2xl font-bold cursor-pointer hover:text-primary-700 transition-all duration-300 transform hover:scale-110", onClick: () => onBackToPublic?.(), children: "Kargo Market" }), _jsx("span", { className: "ml-3 text-sm text-gray-500 bg-gray-100 px-2 py-1 rounded-full", children: "Dashboard" })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "relative", children: _jsxs("button", { className: "flex items-center text-gray-700 hover:text-primary-600 transition-all duration-300 transform hover:scale-110", children: [_jsx(Bell, { size: 20 }), notifications > 0 && (_jsx("span", { className: "absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center animate-bounce-subtle", children: notifications }))] }) }), _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center mr-3 shadow-lg hover:scale-110 transition-all duration-300", children: _jsx(User, { size: 20, className: "text-white" }) }), _jsxs("div", { className: "hidden md:block", children: [_jsxs("p", { className: "text-sm font-medium text-gray-900", children: ["Merhaba, ", profile?.full_name || 'Kullanıcı'] }), _jsxs("select", { value: userRole, onChange: (e) => setUserRole(e.target.value), className: "text-xs text-gray-500 bg-transparent border-none focus:ring-0 p-0 cursor-pointer hover:text-primary-600 transition-colors", "aria-label": "Kullan\u0131c\u0131 rol\u00FC se\u00E7in", title: "Kullan\u0131c\u0131 rol\u00FCn\u00FCz\u00FC de\u011Fi\u015Ftirin", children: [_jsx("option", { value: "alici-satici", children: "Al\u0131c\u0131/Sat\u0131c\u0131" }), _jsx("option", { value: "nakliyeci", children: "Nakliyeci" })] })] })] })] })] }));
};
export default Header;
